# Generated by Django 6.0.2 on 2026-03-03 18:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_initial_balance'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(max_length=20, unique=True)),
                ('instrument_type', models.CharField(choices=[('psx_stock', 'PSX Stock'), ('pk_mutual_fund', 'Mutual Fund (PK)'), ('us_stock', 'US Stock'), ('crypto', 'Crypto'), ('international_fund', 'International Fund')], max_length=20)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('USD', 'USD')], max_length=3)),
                ('platform', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InstrumentPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='investments.instrument')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('instrument', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('units', models.DecimalField(decimal_places=6, max_digits=14)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('brokerage_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_transactions', to='accounts.account')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investments.instrument')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
    ]
