# Generated by Django 6.0.2 on 2026-03-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_instrument_exchangerate_instrumentprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('reinvestment', 'Reinvestment')], max_length=12),
        ),
    ]
