# Generated by Django 6.0.2 on 2026-03-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_investmenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('reinvestment', 'Reinvestment'), ('dividend', 'Dividend')], max_length=12),
        ),
    ]
