# Generated by Django 6.0.2 on 2026-03-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investmenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='api_id',
            field=models.CharField(blank=True, default='', help_text='CoinGecko coin ID (e.g., bitcoin, ethereum, solana)', max_length=100),
        ),
    ]
