# Generated by Django 6.0.2 on 2026-03-08 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_add_instrument_api_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ticker',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='instrument',
            unique_together={('user', 'ticker')},
        ),
    ]
