# Generated by Django 6.0.2 on 2026-03-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
        ('transactions', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='recurring.recurringrule'),
        ),
    ]
