# Generated by Django 6.0.2 on 2026-03-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('transactions', '0003_transaction_recurring_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_type', models.CharField(choices=[('place', 'Place'), ('group', 'Group')], max_length=10)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tag_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'tag_type'), name='unique_tag_name_type')],
            },
        ),
        migrations.CreateModel(
            name='LoanTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_tags', to='loans.loan')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_tags', to='tags.tag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('loan', 'tag'), name='unique_loan_tag')],
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_tags', to='tags.tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_tags', to='transactions.transaction')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'tag'), name='unique_transaction_tag')],
            },
        ),
    ]
