# Generated by Django 6.0.2 on 2026-03-02 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_lent', models.DateField(default=django.utils.timezone.now)),
                ('expected_return', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('repaid', 'Repaid')], default='outstanding', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.account')),
                ('repaid_to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='accounts.account')),
            ],
            options={
                'ordering': ['-date_lent'],
            },
        ),
    ]
