# Generated by Django 6.0.2 on 2026-03-02 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0002_seed_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='transactions.category')),
            ],
            options={
                'ordering': ['-month', 'category__name'],
                'constraints': [models.UniqueConstraint(fields=('category', 'month'), name='unique_budget_category_month')],
            },
        ),
    ]
